package io.smallrye.serial.impl;

import java.io.ObjectInputStream;
import java.lang.constant.ClassDesc;
import java.lang.constant.ConstantDescs;
import java.lang.constant.MethodTypeDesc;
import java.lang.invoke.MethodHandle;
import java.lang.invoke.MethodHandles;
import java.lang.invoke.MethodType;
import java.lang.reflect.RecordComponent;

import io.smallrye.classfile.ClassFile;
import io.smallrye.classfile.CodeBuilder;

/**
 * Generates hidden classes for record deserialization, eliminating boxing overhead.
 * <p>
 * For each record type, a hidden class is generated with a single static method
 * that reads field values from an {@link ObjectInputStream.GetField} and invokes
 * the canonical constructor directly. The generated bytecode references only JDK
 * types, the record class, and its component types — no library types — so it can
 * be defined in any class loader context without linking problems.
 */
public final class RecordFactoryGenerator {

    private static final ClassDesc CD_GET_FIELD = ClassDesc.of("java.io.ObjectInputStream").nested("GetField");
    private static final ClassDesc CD_STRING = ConstantDescs.CD_String;
    private static final ClassDesc CD_OBJECT = ConstantDescs.CD_Object;
    private static final ClassDesc CD_IO_EXCEPTION = ClassDesc.of("java.io.IOException");

    private static final String DESERIALIZE_NAME = "deserialize";

    private RecordFactoryGenerator() {
    }

    /**
     * Generate a factory method handle for the given record class.
     * The returned handle has the type {@code (ObjectInputStream.GetField) → Object}
     * and invokes the canonical constructor directly without boxing.
     *
     * @param recordClass the record class to generate a factory for (must be a record)
     * @return a method handle that deserializes a record from a {@link ObjectInputStream.GetField}
     */
    public static MethodHandle generateFactory(Class<?> recordClass) {
        RecordComponent[] components = recordClass.getRecordComponents();
        ClassDesc recordDesc = classDesc(recordClass);

        // build the constructor descriptor from the component types
        ClassDesc[] paramDescs = new ClassDesc[components.length];
        for (int i = 0; i < components.length; i++) {
            paramDescs[i] = classDesc(components[i].getType());
        }
        MethodTypeDesc ctorDesc = MethodTypeDesc.of(ConstantDescs.CD_void, paramDescs);

        // the generated static method: Object deserialize(GetField) throws Throwable
        MethodTypeDesc methodDesc = MethodTypeDesc.of(CD_OBJECT, CD_GET_FIELD);

        byte[] classBytes = ClassFile.of().build(ClassDesc.of(recordClass.getName() + "$$RecordFactory"), cb -> {
            cb.withVersion(ClassFile.JAVA_17_VERSION, 0);
            cb.withFlags(ClassFile.ACC_FINAL | ClassFile.ACC_SYNTHETIC);
            cb.withMethodBody(DESERIALIZE_NAME, methodDesc,
                    ClassFile.ACC_STATIC | ClassFile.ACC_FINAL,
                    code -> generateMethodBody(code, recordDesc, components, paramDescs, ctorDesc));
        });

        // try to define the hidden class with a lookup rooted at the record class
        MethodHandles.Lookup hiddenLookup = defineHiddenClass(recordClass, classBytes);

        try {
            return hiddenLookup.findStatic(
                    hiddenLookup.lookupClass(),
                    DESERIALIZE_NAME,
                    MethodType.methodType(Object.class, ObjectInputStream.GetField.class));
        } catch (NoSuchMethodException | IllegalAccessException e) {
            throw Util.asError(e);
        }
    }

    /**
     * Generate the method body that reads fields from GetField and constructs the record.
     * <p>
     * The bytecode first reads each component value into a typed local variable
     * using the appropriate {@code GetField.get(String, default)} overload.
     * Then it constructs the record with {@code new}/{@code invokespecial}.
     */
    private static void generateMethodBody(CodeBuilder code, ClassDesc recordDesc,
            RecordComponent[] components, ClassDesc[] paramDescs, MethodTypeDesc ctorDesc) {
        // slot 0 = GetField parameter
        int fieldsSlot = 0;
        int nextSlot = 1;

        // allocate a local slot for each component value
        int[] componentSlots = new int[components.length];
        for (int i = 0; i < components.length; i++) {
            componentSlots[i] = nextSlot;
            nextSlot += slotSize(components[i].getType());
        }

        // phase 1: read each component value from GetField into a local variable
        for (int i = 0; i < components.length; i++) {
            RecordComponent comp = components[i];
            Class<?> type = comp.getType();
            String name = comp.getName();

            code.aload(fieldsSlot);
            code.ldc(name);

            if (type == boolean.class) {
                code.iconst_0();
                code.invokevirtual(CD_GET_FIELD, "get",
                        MethodTypeDesc.of(ConstantDescs.CD_boolean, CD_STRING, ConstantDescs.CD_boolean));
                code.istore(componentSlots[i]);
            } else if (type == byte.class) {
                code.iconst_0();
                code.invokevirtual(CD_GET_FIELD, "get",
                        MethodTypeDesc.of(ConstantDescs.CD_byte, CD_STRING, ConstantDescs.CD_byte));
                code.istore(componentSlots[i]);
            } else if (type == char.class) {
                code.iconst_0();
                code.invokevirtual(CD_GET_FIELD, "get",
                        MethodTypeDesc.of(ConstantDescs.CD_char, CD_STRING, ConstantDescs.CD_char));
                code.istore(componentSlots[i]);
            } else if (type == short.class) {
                code.iconst_0();
                code.invokevirtual(CD_GET_FIELD, "get",
                        MethodTypeDesc.of(ConstantDescs.CD_short, CD_STRING, ConstantDescs.CD_short));
                code.istore(componentSlots[i]);
            } else if (type == int.class) {
                code.iconst_0();
                code.invokevirtual(CD_GET_FIELD, "get",
                        MethodTypeDesc.of(ConstantDescs.CD_int, CD_STRING, ConstantDescs.CD_int));
                code.istore(componentSlots[i]);
            } else if (type == long.class) {
                code.lconst_0();
                code.invokevirtual(CD_GET_FIELD, "get",
                        MethodTypeDesc.of(ConstantDescs.CD_long, CD_STRING, ConstantDescs.CD_long));
                code.lstore(componentSlots[i]);
            } else if (type == float.class) {
                code.fconst_0();
                code.invokevirtual(CD_GET_FIELD, "get",
                        MethodTypeDesc.of(ConstantDescs.CD_float, CD_STRING, ConstantDescs.CD_float));
                code.fstore(componentSlots[i]);
            } else if (type == double.class) {
                code.dconst_0();
                code.invokevirtual(CD_GET_FIELD, "get",
                        MethodTypeDesc.of(ConstantDescs.CD_double, CD_STRING, ConstantDescs.CD_double));
                code.dstore(componentSlots[i]);
            } else {
                code.aconst_null();
                code.invokevirtual(CD_GET_FIELD, "get", MethodTypeDesc.of(CD_OBJECT, CD_STRING, CD_OBJECT));
                code.astore(componentSlots[i]);
            }
        }

        // phase 2: construct the record
        code.new_(recordDesc);
        code.dup();
        for (int i = 0; i < components.length; i++) {
            Class<?> type = components[i].getType();
            if (type == boolean.class || type == byte.class || type == char.class
                    || type == short.class || type == int.class) {
                code.iload(componentSlots[i]);
            } else if (type == long.class) {
                code.lload(componentSlots[i]);
            } else if (type == float.class) {
                code.fload(componentSlots[i]);
            } else if (type == double.class) {
                code.dload(componentSlots[i]);
            } else {
                code.aload(componentSlots[i]);
                // cast Object to the declared component type for the constructor
                if (type != Object.class) {
                    code.checkcast(paramDescs[i]);
                }
            }
        }
        code.invokespecial(recordDesc, "<init>", ctorDesc);
        code.areturn();
    }

    /**
     * Define the hidden class using the best available lookup strategy.
     * Tries non-privileged lookups first, falling back to {@code privateLookupIn}
     * (which requires the target module to {@code opens} the package) only when needed.
     */
    private static MethodHandles.Lookup defineHiddenClass(Class<?> recordClass, byte[] classBytes) {
        // try lookup().in(recordClass) first — no opens required
        try {
            MethodHandles.Lookup lookup = MethodHandles.lookup().in(recordClass);
            return lookup.defineHiddenClass(classBytes, true);
        } catch (IllegalAccessException ignored) {
            // access insufficient, try next strategy
        }

        // try publicLookup().in(recordClass)
        try {
            MethodHandles.Lookup lookup = MethodHandles.publicLookup().in(recordClass);
            return lookup.defineHiddenClass(classBytes, true);
        } catch (IllegalAccessException ignored) {
            // access insufficient, fall back to privateLookupIn
        }

        // fall back to privateLookupIn with NESTMATE (requires opens)
        try {
            MethodHandles.Lookup lookup = MethodHandles.privateLookupIn(recordClass, MethodHandles.lookup());
            return lookup.defineHiddenClass(classBytes, true, MethodHandles.Lookup.ClassOption.NESTMATE);
        } catch (IllegalAccessException e) {
            throw Util.asError(e);
        }
    }

    /**
     * {@return the number of local variable slots required for the given type}
     */
    private static int slotSize(Class<?> type) {
        return (type == long.class || type == double.class) ? 2 : 1;
    }

    /**
     * {@return a {@link ClassDesc} for the given class}
     */
    private static ClassDesc classDesc(Class<?> type) {
        return type.describeConstable().orElseThrow();
    }
}
